import type { LocationTemplate } from "../schemas/location";

export const LOCATION_TEMPLATES: LocationTemplate[] = [
  {
    id: "loc_ruined_harbor",
    regionId: "region_shattered_coast",
    name: "Ruined Harbor",
    type: "landmark",
    connectedLocationIds: ["loc_black_tide_market", "loc_salt_chapel"],
    dangerRating: 2,
    possibleEncounterIds: [
      "enc_rumor_exchange",
      "enc_wounded_traveler",
      "enc_faction_patrol_stop",
    ],
    defaultItemIds: ["item_ration_pack", "item_rusted_charm"],
    defaultNpcIds: ["npc_arch_suspicious_merchant"],
  },
  {
    id: "loc_salt_chapel",
    regionId: "region_shattered_coast",
    name: "Salt Chapel",
    type: "interior",
    connectedLocationIds: ["loc_ruined_harbor", "loc_collapsed_watchtower"],
    dangerRating: 1,
    possibleEncounterIds: ["enc_rumor_exchange", "enc_trapped_cache"],
    defaultItemIds: ["item_chapel_key", "item_healing_tonic"],
    defaultNpcIds: ["npc_arch_shrine_keeper"],
  },
  {
    id: "loc_collapsed_watchtower",
    regionId: "region_shattered_coast",
    name: "Collapsed Watchtower",
    type: "landmark",
    connectedLocationIds: ["loc_salt_chapel", "loc_smuggler_tunnel"],
    dangerRating: 3,
    possibleEncounterIds: ["enc_ambush_narrow_passage", "enc_trapped_cache"],
    defaultItemIds: ["item_signal_flare", "item_salt_worn_dagger"],
    defaultNpcIds: ["npc_arch_exiled_warden"],
  },
  {
    id: "loc_smuggler_tunnel",
    regionId: "region_shattered_coast",
    name: "Smuggler Tunnel",
    type: "dungeon",
    connectedLocationIds: ["loc_collapsed_watchtower", "loc_black_tide_market"],
    dangerRating: 4,
    possibleEncounterIds: ["enc_ambush_narrow_passage", "enc_trapped_cache"],
    defaultItemIds: ["item_smuggler_map_scrap", "item_contraband_ledger"],
    defaultNpcIds: ["npc_arch_scavenger_guide"],
  },
  {
    id: "loc_black_tide_market",
    regionId: "region_shattered_coast",
    name: "Black-Tide Market",
    type: "town",
    connectedLocationIds: ["loc_ruined_harbor", "loc_smuggler_tunnel"],
    dangerRating: 2,
    possibleEncounterIds: ["enc_rumor_exchange", "enc_faction_patrol_stop"],
    defaultItemIds: ["item_contraband_ledger", "item_healing_tonic"],
    defaultNpcIds: ["npc_arch_suspicious_merchant", "npc_arch_scavenger_guide"],
  },
];
